### ISSUE TITLE
Fix invalid code snippet in README

### ISSUE THREAD

**Issue by Dansoftowner** [JPro-one/markdown-javafx-renderer#11]
In the  code snippet at the [Usage](https://github.com/JPro-one/markdown-javafx-renderer#usage) section, the new `MarkdownView` constructor is used but the variable data type is still `MDFXNode`:

```java
import com.sandec.mdfx.MarkdownView;

MDFXNode mdfx = new MarkdownView("your-markdown"); // Invalid data type
content.getStylesheets().add("/com/sandec/mdfx/mdfx-default.css");
```

**Comment by FlorianKirmaier** [comment]
Thank you for reporting this ! It's fixed now.
