### ISSUE TITLE
CSS properties for blockquote colors

### ISSUE THREAD

**Issue by Dansoftowner** [JPro-one/markdown-javafx-renderer#12]
Hi!

Thanks for the awesome enhancements you added to this library.

It would be great to have CSS properties for defining the blockquote's colors.
Like this:
```css
* {
   ...
    /* Blockquotes */
   -mdfx-bc-color-1: cyan; /* the blockquote's border color */
   -mdfx-bc-color-2: lightgray; /* the blockquote's background color */
}
```

Best regards
Daniel

**Comment by FlorianKirmaier** [comment]
Thank you for the suggestion!
This can now be configured via CSS variables!
