### ISSUE TITLE
Make `mdStringProperty` public

### ISSUE THREAD

**Issue by Dansoftowner** [JPro-one/markdown-javafx-renderer#2]
Hi all!

Firstly I want to thank you for creating this awesome library, it's really useful.

I created a markdown editor control for JavaFX (which is available in [this](https://github.com/Dansoftowner/MarkdownEditorControlFX) repo) that uses the `MDFXNode` for rendering the markdown.

![Gif demo](https://raw.githubusercontent.com/Dansoftowner/MarkdownEditorControlFX/master/screenshots/demo-dark.gif)

As you can see, it synchronizes the renderer with the text area **continuously**.

The problem is that the `MDFXNode` class  does not provide a public member that allows to change the content of an already existing `MDFXNode` object. So I looked into the source code, and I found a package-private `StringProperty` reference with the name `mdStringProperty`. Unfortunately, I  have to use *reflection* to access it due to it's restricted visibility.

```java
        try {
            Field field = MDFXNode.class.getDeclaredField("mdStringProperty");
            field.setAccessible(true);
            return (StringProperty) field.get(this);
        } catch (ReflectiveOperationException e) {
            throw new RuntimeException(e);
        }
```
You can view the full code [here](https://github.com/Dansoftowner/MarkdownEditorControlFX/blob/master/src/main/java/com/dansoftware/mdeditor/EditableMDFXNode.java).

Would you create a public getter method for that reference?

Thanks for everything.
Best regards

**Comment by FlorianKirmaier** [comment]
Hi @Dansoftowner ,

nice to hear that the library is used.
Your Markdown Editor looks very good.

I've made a new version 0.1.8, with public methods for the mdString Property, in the usual JavaFX way.

If you want, you could release your TestApplication as an artifact, then I would be able to add it to https://www.jfx-ensemble.com/

Greetings Florian.

**Comment by Dansoftowner** [comment]
Hi @FlorianKirmaier ,

Thanks for the quick response!

I will make a full demo application when I have time, I'll text you if I'm done.
I'm very grateful.
