### ISSUE TITLE
Strikethrough doesn't work

### ISSUE THREAD

**Issue by Dansoftowner** [JPro-one/markdown-javafx-renderer#3]
Hi!

I noticed that strikethrough doesn't work in the renderer.
Is it a bug or simply the `MDFXNode` doesn't support it?

![image](https://user-images.githubusercontent.com/49782833/114048402-d2887880-988a-11eb-9498-9d2c5a233fcb.png)

Greetings Daniel

**Comment by FlorianKirmaier** [comment]
Doesn't seem to be supported. gonna look into it later today. It looks like it's easy to implement.

**Comment by FlorianKirmaier** [comment]
Should work now, check out the new version 0.1.9!

**Comment by FlorianKirmaier** [comment]
You might have to add the folloing to your css file:
```
.markdown-strikethrough {
  -fx-strikethrough: true;
}
```

**Comment by Dansoftowner** [comment]
It works now, thank you so much!
![image](https://user-images.githubusercontent.com/49782833/114188500-7fc1c600-9949-11eb-8d61-f85bad0a3fcf.png)
