### ISSUE TITLE
Ordered list shows up as unordered list

### ISSUE THREAD

**Issue by Dansoftowner** [JPro-one/markdown-javafx-renderer#5]
If I write a numbered list, the `MDFXNode` displayes it as an unordered list.

Is it normal or a misbehaviour?

![image](https://user-images.githubusercontent.com/49782833/114191924-35dadf00-994d-11eb-8fca-7bbee7f166a5.png)

**Comment by FlorianKirmaier** [comment]
Of course, it just wasn't implemented.
But it's now! Finally found some time.
Version 0.2.0 supports ordered lists.
Hope I will fix the other missing features soon too. : )

**Comment by Dansoftowner** [comment]
Thanks for the great work!
