### ISSUE TITLE
Tasklist support

### ISSUE THREAD

**Issue by Dansoftowner** [JPro-one/markdown-javafx-renderer#6]
It seems like `MDFXNode` doesn't support [tasklists](https://github.blog/2014-04-28-task-lists-in-all-markdown-documents/).
It's not a big problem because it's not a part of the "base markdown" specification but you can look into this when you have time.

Expected:
![image](https://user-images.githubusercontent.com/49782833/114206935-24e59a00-995c-11eb-8a94-f745ea0af3a5.png)

Actual:
![image](https://user-images.githubusercontent.com/49782833/114206978-2f079880-995c-11eb-99fc-e1edbea580a6.png)

**Comment by FlorianKirmaier** [comment]
Tasklists is now supported with 0.2.1.
For now we use the Unicode character for the checkbox.
Maybe we will make the node overwriteable in the future.

**Comment by Dansoftowner** [comment]
Wow, great job!
Thanks for your work!
